# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2HOLLauncher_01.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 609)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(450, 0))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_Version = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Version.setObjectName("lbl_Version")
        self.gridLayout_2.addWidget(self.lbl_Version, 8, 0, 1, 2)
        self.gBx_Login = QtWidgets.QGroupBox(self.centralwidget)
        self.gBx_Login.setObjectName("gBx_Login")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gBx_Login)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.LE_Key = QtWidgets.QLineEdit(self.gBx_Login)
        self.LE_Key.setMaxLength(23)
        self.LE_Key.setClearButtonEnabled(True)
        self.LE_Key.setObjectName("LE_Key")
        self.gridLayout_7.addWidget(self.LE_Key, 0, 1, 1, 1)
        self.LE_Username = QtWidgets.QLineEdit(self.gBx_Login)
        self.LE_Username.setStyleSheet("Username")
        self.LE_Username.setInputMask("")
        self.LE_Username.setMaxLength(32)
        self.LE_Username.setFrame(True)
        self.LE_Username.setClearButtonEnabled(True)
        self.LE_Username.setObjectName("LE_Username")
        self.gridLayout_7.addWidget(self.LE_Username, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gBx_Login, 0, 1, 1, 1)
        self.tW_Basic = QtWidgets.QTabWidget(self.centralwidget)
        self.tW_Basic.setTabPosition(QtWidgets.QTabWidget.North)
        self.tW_Basic.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tW_Basic.setObjectName("tW_Basic")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gBx_Video = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBx_Video.sizePolicy().hasHeightForWidth())
        self.gBx_Video.setSizePolicy(sizePolicy)
        self.gBx_Video.setCheckable(False)
        self.gBx_Video.setObjectName("gBx_Video")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gBx_Video)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.gBx_Video)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem, 0, 0, 1, 1)
        self.cBx_VSync = QtWidgets.QCheckBox(self.frame_8)
        self.cBx_VSync.setChecked(True)
        self.cBx_VSync.setObjectName("cBx_VSync")
        self.gridLayout_27.addWidget(self.cBx_VSync, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem1, 0, 3, 1, 1)
        self.cBx_Fullscreen = QtWidgets.QCheckBox(self.frame_8)
        self.cBx_Fullscreen.setChecked(True)
        self.cBx_Fullscreen.setObjectName("cBx_Fullscreen")
        self.gridLayout_27.addWidget(self.cBx_Fullscreen, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem2, 0, 6, 1, 1)
        self.Btn_Borderless_Reset = QtWidgets.QPushButton(self.frame_8)
        self.Btn_Borderless_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_Borderless_Reset.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Reset_16px_Hover.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Borderless_Reset.setIcon(icon)
        self.Btn_Borderless_Reset.setIconSize(QtCore.QSize(16, 16))
        self.Btn_Borderless_Reset.setDefault(False)
        self.Btn_Borderless_Reset.setFlat(True)
        self.Btn_Borderless_Reset.setObjectName("Btn_Borderless_Reset")
        self.gridLayout_27.addWidget(self.Btn_Borderless_Reset, 0, 8, 1, 1)
        self.cBx_Borderless = QtWidgets.QCheckBox(self.frame_8)
        self.cBx_Borderless.setChecked(True)
        self.cBx_Borderless.setObjectName("cBx_Borderless")
        self.gridLayout_27.addWidget(self.cBx_Borderless, 0, 7, 1, 1)
        self.Btn_Fullscreen_Reset = QtWidgets.QPushButton(self.frame_8)
        self.Btn_Fullscreen_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_Fullscreen_Reset.setText("")
        self.Btn_Fullscreen_Reset.setIcon(icon)
        self.Btn_Fullscreen_Reset.setIconSize(QtCore.QSize(16, 16))
        self.Btn_Fullscreen_Reset.setFlat(True)
        self.Btn_Fullscreen_Reset.setObjectName("Btn_Fullscreen_Reset")
        self.gridLayout_27.addWidget(self.Btn_Fullscreen_Reset, 0, 5, 1, 1)
        self.Btn_VSync_Reset = QtWidgets.QPushButton(self.frame_8)
        self.Btn_VSync_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_VSync_Reset.setText("")
        self.Btn_VSync_Reset.setIcon(icon)
        self.Btn_VSync_Reset.setFlat(True)
        self.Btn_VSync_Reset.setObjectName("Btn_VSync_Reset")
        self.gridLayout_27.addWidget(self.Btn_VSync_Reset, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame_8, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.gBx_Video)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.lb_MouePointer = QtWidgets.QLabel(self.frame_7)
        self.lb_MouePointer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_MouePointer.setObjectName("lb_MouePointer")
        self.gridLayout_26.addWidget(self.lb_MouePointer, 1, 0, 1, 1)
        self.lb_Resolution = QtWidgets.QLabel(self.frame_7)
        self.lb_Resolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Resolution.setObjectName("lb_Resolution")
        self.gridLayout_26.addWidget(self.lb_Resolution, 0, 0, 1, 1)
        self.Btn_Resolution = QtWidgets.QComboBox(self.frame_7)
        self.Btn_Resolution.setObjectName("Btn_Resolution")
        self.Btn_Resolution.addItem("")
        self.Btn_Resolution.addItem("")
        self.Btn_Resolution.addItem("")
        self.gridLayout_26.addWidget(self.Btn_Resolution, 0, 1, 1, 1)
        self.Btn_MousePointer = QtWidgets.QComboBox(self.frame_7)
        self.Btn_MousePointer.setObjectName("Btn_MousePointer")
        self.Btn_MousePointer.addItem("")
        self.Btn_MousePointer.addItem("")
        self.Btn_MousePointer.addItem("")
        self.gridLayout_26.addWidget(self.Btn_MousePointer, 1, 1, 1, 1)
        self.Btn_MousePointer_Reset = QtWidgets.QPushButton(self.frame_7)
        self.Btn_MousePointer_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_MousePointer_Reset.setText("")
        self.Btn_MousePointer_Reset.setIcon(icon)
        self.Btn_MousePointer_Reset.setFlat(True)
        self.Btn_MousePointer_Reset.setObjectName("Btn_MousePointer_Reset")
        self.gridLayout_26.addWidget(self.Btn_MousePointer_Reset, 1, 2, 1, 1)
        self.Btn_Resolution_Reset = QtWidgets.QPushButton(self.frame_7)
        self.Btn_Resolution_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_Resolution_Reset.setText("")
        self.Btn_Resolution_Reset.setIcon(icon)
        self.Btn_Resolution_Reset.setFlat(True)
        self.Btn_Resolution_Reset.setObjectName("Btn_Resolution_Reset")
        self.gridLayout_26.addWidget(self.Btn_Resolution_Reset, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame_7, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gBx_Video, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gBx_Audio = QtWidgets.QGroupBox(self.tab)
        self.gBx_Audio.setObjectName("gBx_Audio")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gBx_Audio)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hS_MasterVolume = QtWidgets.QSlider(self.gBx_Audio)
        self.hS_MasterVolume.setEnabled(True)
        self.hS_MasterVolume.setAcceptDrops(False)
        self.hS_MasterVolume.setMaximum(100)
        self.hS_MasterVolume.setSingleStep(5)
        self.hS_MasterVolume.setProperty("value", 30)
        self.hS_MasterVolume.setSliderPosition(30)
        self.hS_MasterVolume.setTracking(True)
        self.hS_MasterVolume.setOrientation(QtCore.Qt.Horizontal)
        self.hS_MasterVolume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hS_MasterVolume.setTickInterval(10)
        self.hS_MasterVolume.setObjectName("hS_MasterVolume")
        self.gridLayout_5.addWidget(self.hS_MasterVolume, 1, 1, 1, 1)
        self.lbl_MusicVolume_value = QtWidgets.QLabel(self.gBx_Audio)
        self.lbl_MusicVolume_value.setEnabled(False)
        self.lbl_MusicVolume_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_MusicVolume_value.setObjectName("lbl_MusicVolume_value")
        self.gridLayout_5.addWidget(self.lbl_MusicVolume_value, 2, 2, 1, 1)
        self.lbl_MasterVolume = QtWidgets.QLabel(self.gBx_Audio)
        self.lbl_MasterVolume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_MasterVolume.setObjectName("lbl_MasterVolume")
        self.gridLayout_5.addWidget(self.lbl_MasterVolume, 1, 0, 1, 1)
        self.hS_SoundVolume = QtWidgets.QSlider(self.gBx_Audio)
        self.hS_SoundVolume.setMaximum(100)
        self.hS_SoundVolume.setSingleStep(5)
        self.hS_SoundVolume.setProperty("value", 100)
        self.hS_SoundVolume.setSliderPosition(100)
        self.hS_SoundVolume.setOrientation(QtCore.Qt.Horizontal)
        self.hS_SoundVolume.setInvertedAppearance(False)
        self.hS_SoundVolume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hS_SoundVolume.setTickInterval(10)
        self.hS_SoundVolume.setObjectName("hS_SoundVolume")
        self.gridLayout_5.addWidget(self.hS_SoundVolume, 3, 1, 1, 1)
        self.lbl_MasterVolume_value = QtWidgets.QLabel(self.gBx_Audio)
        self.lbl_MasterVolume_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_MasterVolume_value.setObjectName("lbl_MasterVolume_value")
        self.gridLayout_5.addWidget(self.lbl_MasterVolume_value, 1, 2, 1, 1)
        self.hS_MusicVolume = QtWidgets.QSlider(self.gBx_Audio)
        self.hS_MusicVolume.setEnabled(False)
        self.hS_MusicVolume.setMaximum(100)
        self.hS_MusicVolume.setSingleStep(5)
        self.hS_MusicVolume.setProperty("value", 80)
        self.hS_MusicVolume.setSliderPosition(80)
        self.hS_MusicVolume.setOrientation(QtCore.Qt.Horizontal)
        self.hS_MusicVolume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hS_MusicVolume.setTickInterval(10)
        self.hS_MusicVolume.setObjectName("hS_MusicVolume")
        self.gridLayout_5.addWidget(self.hS_MusicVolume, 2, 1, 1, 1)
        self.lbl_SoundVolume = QtWidgets.QLabel(self.gBx_Audio)
        self.lbl_SoundVolume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_SoundVolume.setObjectName("lbl_SoundVolume")
        self.gridLayout_5.addWidget(self.lbl_SoundVolume, 3, 0, 1, 1)
        self.lbl_SoundVolume_value = QtWidgets.QLabel(self.gBx_Audio)
        self.lbl_SoundVolume_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_SoundVolume_value.setObjectName("lbl_SoundVolume_value")
        self.gridLayout_5.addWidget(self.lbl_SoundVolume_value, 3, 2, 1, 1)
        self.lbl_MusicVolume = QtWidgets.QLabel(self.gBx_Audio)
        self.lbl_MusicVolume.setEnabled(False)
        self.lbl_MusicVolume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_MusicVolume.setObjectName("lbl_MusicVolume")
        self.gridLayout_5.addWidget(self.lbl_MusicVolume, 2, 0, 1, 1)
        self.Btn_MasterVolume_Reset = QtWidgets.QPushButton(self.gBx_Audio)
        self.Btn_MasterVolume_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_MasterVolume_Reset.setObjectName("Btn_MasterVolume_Reset")
        self.gridLayout_5.addWidget(self.Btn_MasterVolume_Reset, 1, 3, 1, 1)
        self.Btn_MusicVolume_Reset = QtWidgets.QPushButton(self.gBx_Audio)
        self.Btn_MusicVolume_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_MusicVolume_Reset.setObjectName("Btn_MusicVolume_Reset")
        self.gridLayout_5.addWidget(self.Btn_MusicVolume_Reset, 2, 3, 1, 1)
        self.lbl_SoundVolume_Reset = QtWidgets.QPushButton(self.gBx_Audio)
        self.lbl_SoundVolume_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.lbl_SoundVolume_Reset.setObjectName("lbl_SoundVolume_Reset")
        self.gridLayout_5.addWidget(self.lbl_SoundVolume_Reset, 3, 3, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gBx_Audio)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem3, 0, 6, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_36.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_17.addWidget(self.pushButton_36, 0, 5, 1, 1)
        self.cBx_PlayAudio = QtWidgets.QCheckBox(self.frame_2)
        self.cBx_PlayAudio.setChecked(True)
        self.cBx_PlayAudio.setObjectName("cBx_PlayAudio")
        self.gridLayout_17.addWidget(self.cBx_PlayAudio, 0, 1, 1, 1)
        self.cBx = QtWidgets.QCheckBox(self.frame_2)
        self.cBx.setChecked(False)
        self.cBx.setObjectName("cBx")
        self.gridLayout_17.addWidget(self.cBx, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem4, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem5, 0, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_17.addWidget(self.checkBox_11, 0, 7, 1, 1)
        self.Btn_PlayAudio_Reset = QtWidgets.QPushButton(self.frame_2)
        self.Btn_PlayAudio_Reset.setMaximumSize(QtCore.QSize(15, 15))
        self.Btn_PlayAudio_Reset.setObjectName("Btn_PlayAudio_Reset")
        self.gridLayout_17.addWidget(self.Btn_PlayAudio_Reset, 0, 2, 1, 1)
        self.pushButton_59 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_59.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_59.setObjectName("pushButton_59")
        self.gridLayout_17.addWidget(self.pushButton_59, 0, 8, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 4)
        self.gridLayout_3.addWidget(self.gBx_Audio, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gBx_Network = QtWidgets.QGroupBox(self.tab)
        self.gBx_Network.setObjectName("gBx_Network")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gBx_Network)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_Server = QtWidgets.QLabel(self.gBx_Network)
        self.lbl_Server.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Server.setObjectName("lbl_Server")
        self.gridLayout_4.addWidget(self.lbl_Server, 0, 0, 1, 1)
        self.cBx_Server = QtWidgets.QComboBox(self.gBx_Network)
        self.cBx_Server.setObjectName("cBx_Server")
        self.cBx_Server.addItem("")
        self.cBx_Server.addItem("")
        self.gridLayout_4.addWidget(self.cBx_Server, 0, 1, 1, 2)
        self.lbl_Address = QtWidgets.QLabel(self.gBx_Network)
        self.lbl_Address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Address.setObjectName("lbl_Address")
        self.gridLayout_4.addWidget(self.lbl_Address, 1, 0, 1, 1)
        self.LE_Address = QtWidgets.QLineEdit(self.gBx_Network)
        self.LE_Address.setEnabled(False)
        self.LE_Address.setReadOnly(False)
        self.LE_Address.setClearButtonEnabled(True)
        self.LE_Address.setObjectName("LE_Address")
        self.gridLayout_4.addWidget(self.LE_Address, 1, 1, 1, 1)
        self.LE_Port = QtWidgets.QLineEdit(self.gBx_Network)
        self.LE_Port.setEnabled(False)
        self.LE_Port.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LE_Port.setReadOnly(True)
        self.LE_Port.setClearButtonEnabled(True)
        self.LE_Port.setObjectName("LE_Port")
        self.gridLayout_4.addWidget(self.LE_Port, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.gBx_Network, 2, 0, 1, 1, QtCore.Qt.AlignTop)
        self.tW_Basic.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 376, 339))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 0, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_3.setMaximumSize(QtCore.QSize(55, 16777215))
        self.doubleSpinBox_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_3.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_3.setSuffix("")
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setProperty("value", 10.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_13.addWidget(self.doubleSpinBox_3, 0, 1, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_37.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_13.addWidget(self.pushButton_37, 0, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_38.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout.addWidget(self.pushButton_38, 0, 4, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 1, 7, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_48.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout.addWidget(self.pushButton_48, 4, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 7, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 6, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 7, 6, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_43.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout.addWidget(self.pushButton_43, 6, 4, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 4, 3, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 6, 7, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_47.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout.addWidget(self.pushButton_47, 3, 8, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_51.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout.addWidget(self.pushButton_51, 7, 8, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 7, 7, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_40.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout.addWidget(self.pushButton_40, 3, 4, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_45.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout.addWidget(self.pushButton_45, 0, 8, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 4, 7, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 3, 3, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 0, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 3, 7, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 5, 3, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_49.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout.addWidget(self.pushButton_49, 5, 8, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 1, 6, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 6, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 6, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_50.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout.addWidget(self.pushButton_50, 6, 8, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 6, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_42.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout.addWidget(self.pushButton_42, 5, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 2, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_44.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout.addWidget(self.pushButton_44, 7, 4, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_39.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout.addWidget(self.pushButton_39, 1, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 6, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 5, 7, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_46.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout.addWidget(self.pushButton_46, 1, 8, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_41.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout.addWidget(self.pushButton_41, 4, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_5, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem8, 3, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.addWidget(self.scrollArea_2, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 376, 339))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox.setProperty("value", 2.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_30.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.doubleSpinBox_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_30.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_30.addWidget(self.label_12, 1, 0, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_56.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout_30.addWidget(self.pushButton_56, 0, 2, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_57.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout_30.addWidget(self.pushButton_57, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_30.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_11, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem9, 2, 0, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_52.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout_18.addWidget(self.pushButton_52, 1, 3, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_18.addWidget(self.checkBox_6, 1, 1, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_53.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout_18.addWidget(self.pushButton_53, 2, 3, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_54.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout_18.addWidget(self.pushButton_54, 2, 6, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 1, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_18.addWidget(self.checkBox_7, 2, 1, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_55.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout_18.addWidget(self.pushButton_55, 1, 6, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_18.addWidget(self.checkBox_15, 1, 5, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_18.addWidget(self.checkBox_19, 2, 5, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem11, 1, 4, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem12, 2, 4, 1, 1)
        self.gridLayout_19.addWidget(self.frame_3, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem13, 2, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_9.addWidget(self.scrollArea_3, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 376, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_16.addWidget(self.frame_4, 3, 0, 1, 1, QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_28.addWidget(self.checkBox_12, 1, 4, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_22.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_28.addWidget(self.pushButton_22, 1, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem14, 0, 3, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_20.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_28.addWidget(self.pushButton_20, 1, 2, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_28.addWidget(self.checkBox_8, 0, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_21.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_28.addWidget(self.pushButton_21, 0, 5, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_19.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_28.addWidget(self.pushButton_19, 0, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_28.addWidget(self.checkBox_9, 0, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem15, 1, 3, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_28.addWidget(self.checkBox_16, 1, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem16, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_9, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_25.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_29.addWidget(self.pushButton_25, 2, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox.setMaximum(256)
        self.spinBox.setProperty("value", 130)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_29.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_29.addWidget(self.label_28, 0, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBox_3.setProperty("showGroupSeparator", True)
        self.spinBox_3.setMaximum(99999)
        self.spinBox_3.setProperty("value", 44100)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_29.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_23.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_29.addWidget(self.pushButton_23, 0, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_29.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_29.addWidget(self.label_29, 1, 0, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_26.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_29.addWidget(self.pushButton_26, 3, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_24.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_29.addWidget(self.pushButton_24, 1, 2, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_2.setMinimum(256)
        self.spinBox_2.setMaximum(4096)
        self.spinBox_2.setProperty("value", 1024)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_29.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBox_4.setProperty("showGroupSeparator", True)
        self.spinBox_4.setMaximum(99999)
        self.spinBox_4.setProperty("value", 20)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_29.addWidget(self.spinBox_4, 3, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_29.addWidget(self.label_35, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_10, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem17, 4, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_15.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_6)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, -21, 359, 360))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_11.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_21.addWidget(self.pushButton_11, 0, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_5)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_21.addWidget(self.label_37, 0, 0, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_4.setMaximum(10.0)
        self.doubleSpinBox_4.setProperty("value", 3.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_21.addWidget(self.doubleSpinBox_4, 3, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_21.addWidget(self.pushButton_8, 5, 3, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_7.setMaximum(10.0)
        self.doubleSpinBox_7.setProperty("value", 0.54)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_21.addWidget(self.doubleSpinBox_7, 2, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_21.addWidget(self.pushButton_9, 3, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_10.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_21.addWidget(self.pushButton_10, 2, 3, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_6.setDecimals(1)
        self.doubleSpinBox_6.setMaximum(10.0)
        self.doubleSpinBox_6.setProperty("value", 1.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_21.addWidget(self.doubleSpinBox_6, 6, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_5)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_21.addWidget(self.label_33, 5, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_8.setMaximum(10.0)
        self.doubleSpinBox_8.setProperty("value", 0.75)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_21.addWidget(self.doubleSpinBox_8, 0, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_5)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_21.addWidget(self.label_34, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_5)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_21.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_5)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_21.addWidget(self.label_36, 2, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBox_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_5.setMaximum(10.0)
        self.doubleSpinBox_5.setProperty("value", 0.35)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_21.addWidget(self.doubleSpinBox_5, 5, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_21.addWidget(self.pushButton_7, 6, 3, 1, 1)
        self.gridLayout_24.addWidget(self.frame_5, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_24.addWidget(self.line, 2, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem18, 2, 4, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox_7)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.gridLayout_22.addWidget(self.label_59, 2, 5, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_3.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_22.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lineEdit_22.setMaxLength(1)
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_22.addWidget(self.lineEdit_22, 2, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_6.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_22.addWidget(self.pushButton_6, 2, 8, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lineEdit_21.setMaxLength(1)
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_22.addWidget(self.lineEdit_21, 0, 7, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lineEdit_23.setMaxLength(1)
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_22.addWidget(self.lineEdit_23, 2, 7, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem19, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_4.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_22.addWidget(self.pushButton_4, 0, 8, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lineEdit_19.setMaxLength(1)
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_22.addWidget(self.lineEdit_19, 0, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_22.addWidget(self.label_39, 0, 6, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_22.addWidget(self.label_43, 2, 6, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_5.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_22.addWidget(self.pushButton_5, 2, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_7)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_22.addWidget(self.label_38, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_22.addWidget(self.label_42, 2, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem20, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem21, 2, 0, 1, 1)
        self.gridLayout_24.addWidget(self.groupBox_7, 3, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_16.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_25.addWidget(self.pushButton_16, 1, 6, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.frame_6)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.gridLayout_25.addWidget(self.label_47, 1, 4, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_14.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_25.addWidget(self.pushButton_14, 3, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_13.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_25.addWidget(self.pushButton_13, 1, 2, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_25.addWidget(self.checkBox_5, 3, 1, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_25.addWidget(self.checkBox_17, 1, 5, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem22, 0, 4, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem23, 0, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem24, 3, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_25.addWidget(self.checkBox_14, 0, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_15.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_25.addWidget(self.pushButton_15, 0, 6, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_13.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_25.addWidget(self.checkBox_13, 0, 5, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_12.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_25.addWidget(self.pushButton_12, 0, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_6)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.gridLayout_25.addWidget(self.label_48, 3, 4, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_17.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_25.addWidget(self.pushButton_17, 3, 6, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_25.addWidget(self.checkBox_20, 3, 5, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_25.addWidget(self.checkBox_18, 1, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem25, 1, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_6, 1, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem26, 4, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_20.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.gridLayout_8.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.tW_Basic.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tW_Basic, 2, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Btn_SaveSettings = QtWidgets.QPushButton(self.frame)
        self.Btn_SaveSettings.setMinimumSize(QtCore.QSize(0, 35))
        self.Btn_SaveSettings.setWhatsThis("")
        self.Btn_SaveSettings.setObjectName("Btn_SaveSettings")
        self.gridLayout_14.addWidget(self.Btn_SaveSettings, 0, 1, 1, 1)
        self.Btn_Play = QtWidgets.QPushButton(self.frame)
        self.Btn_Play.setMinimumSize(QtCore.QSize(0, 35))
        self.Btn_Play.setObjectName("Btn_Play")
        self.gridLayout_14.addWidget(self.Btn_Play, 0, 2, 1, 1)
        self.Btn_ResetAllSettings = QtWidgets.QPushButton(self.frame)
        self.Btn_ResetAllSettings.setMinimumSize(QtCore.QSize(0, 35))
        self.Btn_ResetAllSettings.setWhatsThis("")
        self.Btn_ResetAllSettings.setObjectName("Btn_ResetAllSettings")
        self.gridLayout_14.addWidget(self.Btn_ResetAllSettings, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset_Settings = QtWidgets.QAction(MainWindow)
        self.actionReset_Settings.setObjectName("actionReset_Settings")
        self.actionSave_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.menuFile.addAction(self.actionReset_Settings)
        self.menuFile.addAction(self.actionSave_Settings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tW_Basic.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2HOL Launcher"))
        self.lbl_Version.setStatusTip(_translate("MainWindow", "Game Version | Publish Date"))
        self.lbl_Version.setText(_translate("MainWindow", "v256 | 13.09.2019"))
        self.gBx_Login.setTitle(_translate("MainWindow", "Login"))
        self.LE_Key.setText(_translate("MainWindow", "BNNFY-9JYDW-SXFKH-XXXXX"))
        self.LE_Key.setPlaceholderText(_translate("MainWindow", "Key"))
        self.LE_Username.setToolTip(_translate("MainWindow", "Username"))
        self.LE_Username.setAccessibleName(_translate("MainWindow", "Username"))
        self.LE_Username.setAccessibleDescription(_translate("MainWindow", "Username"))
        self.LE_Username.setText(_translate("MainWindow", "ionarn-2637"))
        self.LE_Username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.gBx_Video.setTitle(_translate("MainWindow", "Video"))
        self.cBx_VSync.setText(_translate("MainWindow", "Use V-Sync"))
        self.cBx_Fullscreen.setText(_translate("MainWindow", "Fullscreen"))
        self.cBx_Borderless.setText(_translate("MainWindow", "Borderless"))
        self.lb_MouePointer.setText(_translate("MainWindow", "Mouse Pointer"))
        self.lb_Resolution.setText(_translate("MainWindow", "Resolution"))
        self.Btn_Resolution.setItemText(0, _translate("MainWindow", "1920x1080"))
        self.Btn_Resolution.setItemText(1, _translate("MainWindow", "1280x720"))
        self.Btn_Resolution.setItemText(2, _translate("MainWindow", "1600x900"))
        self.Btn_MousePointer.setItemText(0, _translate("MainWindow", "Native"))
        self.Btn_MousePointer.setItemText(1, _translate("MainWindow", "Drawn"))
        self.Btn_MousePointer.setItemText(2, _translate("MainWindow", "Both"))
        self.gBx_Audio.setTitle(_translate("MainWindow", "Audio"))
        self.lbl_MusicVolume_value.setText(_translate("MainWindow", "80"))
        self.lbl_MasterVolume.setText(_translate("MainWindow", "Master Volume"))
        self.lbl_MasterVolume_value.setText(_translate("MainWindow", "30"))
        self.lbl_SoundVolume.setText(_translate("MainWindow", "Sound Effects Volume"))
        self.lbl_SoundVolume_value.setText(_translate("MainWindow", "100"))
        self.lbl_MusicVolume.setText(_translate("MainWindow", "Music Volume"))
        self.Btn_MasterVolume_Reset.setText(_translate("MainWindow", "R"))
        self.Btn_MusicVolume_Reset.setText(_translate("MainWindow", "R"))
        self.lbl_SoundVolume_Reset.setText(_translate("MainWindow", "R"))
        self.pushButton_36.setText(_translate("MainWindow", "R"))
        self.cBx_PlayAudio.setText(_translate("MainWindow", "Play Audio"))
        self.cBx.setText(_translate("MainWindow", "Play Music"))
        self.checkBox_11.setText(_translate("MainWindow", "Play Sound"))
        self.Btn_PlayAudio_Reset.setText(_translate("MainWindow", "R"))
        self.pushButton_59.setText(_translate("MainWindow", "R"))
        self.gBx_Network.setTitle(_translate("MainWindow", "Network"))
        self.lbl_Server.setText(_translate("MainWindow", "Server"))
        self.cBx_Server.setItemText(0, _translate("MainWindow", "Two Hours One Life"))
        self.cBx_Server.setItemText(1, _translate("MainWindow", "Custom Server Address"))
        self.lbl_Address.setText(_translate("MainWindow", "Address"))
        self.LE_Address.setText(_translate("MainWindow", "play.twohoursonelife.com"))
        self.LE_Address.setPlaceholderText(_translate("MainWindow", "play.twohoursonelife.com"))
        self.LE_Port.setText(_translate("MainWindow", "8005"))
        self.LE_Port.setPlaceholderText(_translate("MainWindow", "8005"))
        self.tW_Basic.setTabText(self.tW_Basic.indexOf(self.tab), _translate("MainWindow", "Basic Settings"))
        self.groupBox_6.setTitle(_translate("MainWindow", "General Emotion Settings"))
        self.label_27.setText(_translate("MainWindow", "Emotion Duration (sec)"))
        self.pushButton_37.setText(_translate("MainWindow", "R"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Emotion Wording"))
        self.pushButton_38.setText(_translate("MainWindow", "R"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "/ill"))
        self.pushButton_48.setText(_translate("MainWindow", "R"))
        self.label_16.setText(_translate("MainWindow", "Sad"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "/blush"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "/joy"))
        self.label_23.setText(_translate("MainWindow", "Hmph"))
        self.label_26.setText(_translate("MainWindow", "Shock"))
        self.pushButton_43.setText(_translate("MainWindow", "R"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "/sad"))
        self.lineEdit_17.setPlaceholderText(_translate("MainWindow", "/oreally"))
        self.pushButton_47.setText(_translate("MainWindow", "R"))
        self.pushButton_51.setText(_translate("MainWindow", "R"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "/shock"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "/happy"))
        self.pushButton_40.setText(_translate("MainWindow", "R"))
        self.pushButton_45.setText(_translate("MainWindow", "R"))
        self.lineEdit_15.setPlaceholderText(_translate("MainWindow", "/hmph"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "/angry"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "/hubba"))
        self.label_17.setText(_translate("MainWindow", "Devious"))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "/yoohoo"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "/devious"))
        self.pushButton_49.setText(_translate("MainWindow", "R"))
        self.label_21.setText(_translate("MainWindow", "Ill"))
        self.label_18.setText(_translate("MainWindow", "Joy"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "/mad"))
        self.label_20.setText(_translate("MainWindow", "Hubba"))
        self.pushButton_50.setText(_translate("MainWindow", "R"))
        self.label_24.setText(_translate("MainWindow", "Love"))
        self.label_25.setText(_translate("MainWindow", "Oh really?"))
        self.label_14.setText(_translate("MainWindow", "Mad"))
        self.pushButton_42.setText(_translate("MainWindow", "R"))
        self.label_19.setText(_translate("MainWindow", "Blush"))
        self.label_15.setText(_translate("MainWindow", "Angry"))
        self.pushButton_44.setText(_translate("MainWindow", "R"))
        self.pushButton_39.setText(_translate("MainWindow", "R"))
        self.label_22.setText(_translate("MainWindow", "Yoohoo"))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "/love"))
        self.label_13.setText(_translate("MainWindow", "Happy"))
        self.pushButton_46.setText(_translate("MainWindow", "R"))
        self.pushButton_41.setText(_translate("MainWindow", "R"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Emotions"))
        self.label_12.setText(_translate("MainWindow", "HUD FOV Scale"))
        self.pushButton_56.setText(_translate("MainWindow", "R"))
        self.pushButton_57.setText(_translate("MainWindow", "R"))
        self.label_9.setText(_translate("MainWindow", "Game FOV Scale"))
        self.pushButton_52.setText(_translate("MainWindow", "R"))
        self.checkBox_6.setText(_translate("MainWindow", "Hide Game UI"))
        self.pushButton_53.setText(_translate("MainWindow", "R"))
        self.pushButton_54.setText(_translate("MainWindow", "R"))
        self.checkBox_7.setText(_translate("MainWindow", "Half Frame Rate"))
        self.pushButton_55.setText(_translate("MainWindow", "R"))
        self.checkBox_15.setText(_translate("MainWindow", "Force Big Pointer"))
        self.checkBox_19.setText(_translate("MainWindow", "Show FPS"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "HUD"))
        self.checkBox_12.setText(_translate("MainWindow", "Hide Playback Display"))
        self.pushButton_22.setText(_translate("MainWindow", "R"))
        self.pushButton_20.setText(_translate("MainWindow", "R"))
        self.checkBox_8.setText(_translate("MainWindow", "Record Game"))
        self.pushButton_21.setText(_translate("MainWindow", "R"))
        self.pushButton_19.setText(_translate("MainWindow", "R"))
        self.checkBox_9.setText(_translate("MainWindow", "Record Audio"))
        self.checkBox_16.setText(_translate("MainWindow", "Speed Control Keys"))
        self.pushButton_25.setText(_translate("MainWindow", "R"))
        self.label_28.setText(_translate("MainWindow", "Record Audio Length (in s)"))
        self.pushButton_23.setText(_translate("MainWindow", "R"))
        self.label_31.setText(_translate("MainWindow", "Sound Sample Rate (in kHz)"))
        self.label_29.setText(_translate("MainWindow", "Sound Buffer Size"))
        self.pushButton_26.setText(_translate("MainWindow", "R"))
        self.pushButton_24.setText(_translate("MainWindow", "R"))
        self.label_35.setText(_translate("MainWindow", "Keep Recordings"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Recording"))
        self.pushButton_11.setText(_translate("MainWindow", "R"))
        self.label_37.setText(_translate("MainWindow", "Baby Body Down Factor"))
        self.pushButton_8.setText(_translate("MainWindow", "R"))
        self.pushButton_9.setText(_translate("MainWindow", "R"))
        self.pushButton_10.setText(_translate("MainWindow", "R"))
        self.label_33.setText(_translate("MainWindow", "Old Head Down Factor"))
        self.label_34.setText(_translate("MainWindow", "Cursor Speed"))
        self.label_32.setText(_translate("MainWindow", "Old Head Forward Factor"))
        self.label_36.setText(_translate("MainWindow", "Baby Head Down Factor"))
        self.pushButton_7.setText(_translate("MainWindow", "R"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Keybindings"))
        self.pushButton_3.setText(_translate("MainWindow", "R"))
        self.lineEdit_22.setText(_translate("MainWindow", "A"))
        self.pushButton_6.setText(_translate("MainWindow", "R"))
        self.lineEdit_21.setText(_translate("MainWindow", "S"))
        self.lineEdit_23.setText(_translate("MainWindow", "D"))
        self.pushButton_4.setText(_translate("MainWindow", "R"))
        self.lineEdit_19.setText(_translate("MainWindow", "W"))
        self.label_39.setText(_translate("MainWindow", "Walk Down"))
        self.label_43.setText(_translate("MainWindow", "Walk Right"))
        self.pushButton_5.setText(_translate("MainWindow", "R"))
        self.label_38.setText(_translate("MainWindow", "Walk Up"))
        self.label_42.setText(_translate("MainWindow", "Walk Left"))
        self.pushButton_16.setText(_translate("MainWindow", "R"))
        self.pushButton_14.setText(_translate("MainWindow", "R"))
        self.pushButton_13.setText(_translate("MainWindow", "R"))
        self.checkBox_5.setText(_translate("MainWindow", "Pause On Minimize"))
        self.checkBox_17.setText(_translate("MainWindow", "Enable Live Triggers"))
        self.checkBox_14.setText(_translate("MainWindow", "Hard To Quite Mode"))
        self.pushButton_15.setText(_translate("MainWindow", "R"))
        self.checkBox_13.setText(_translate("MainWindow", "Ground Tile Blur Radius"))
        self.pushButton_12.setText(_translate("MainWindow", "R"))
        self.pushButton_17.setText(_translate("MainWindow", "R"))
        self.checkBox_20.setText(_translate("MainWindow", "Tutorial Done"))
        self.checkBox_18.setText(_translate("MainWindow", "Check Spelling"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Miscellaneous"))
        self.tW_Basic.setTabText(self.tW_Basic.indexOf(self.tab_2), _translate("MainWindow", "Advanced Settings"))
        self.Btn_SaveSettings.setStatusTip(_translate("MainWindow", "Saves the Settings"))
        self.Btn_SaveSettings.setText(_translate("MainWindow", "Save Settings"))
        self.Btn_Play.setStatusTip(_translate("MainWindow", "Launches the game"))
        self.Btn_Play.setText(_translate("MainWindow", "Play"))
        self.Btn_ResetAllSettings.setStatusTip(_translate("MainWindow", "Saves the Settings"))
        self.Btn_ResetAllSettings.setText(_translate("MainWindow", "Reset All Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionReset_Settings.setText(_translate("MainWindow", "Reset Settings"))
        self.actionSave_Settings.setText(_translate("MainWindow", "Save Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
